### ISSUE TITLE
publish as package

### ISSUE THREAD

**Issue by bwbohl** [peterstadler/digilib-docker#1]
it would be great to see this published either in ghcr or on dockerlib ;-)

**Comment by peterstadler** [comment]
Sorry for the delay, this seems to have slipped my attention!
The docker image is available from https://hub.docker.com/r/stadlerpeter/digilib-docker. Is that what you're looking for?

**Comment by peterstadler** [comment]
no response, closing …

**Comment by bwbohl** [comment]
much more impatient than I was :-p
